This test was aborted because of a previous failure (see below).

This test was not run because a prior test failed (see below). As a result, this test counts as failed.

Expected `guess_the_vector_N_up` to call `assert`.
